### PR TITLE
French translation added

### PR DESCRIPTION
**Pull request by ghost**
Thanks for your amazing work!
Here is a proposal of translation in French.
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translations could be more easily reviewed by Ubuntu Translators?

### CODE REVIEW

**Comment by avisoftware** [comment]
First thank you very much! 
This app is on BETA and i will add more string to it... So the best thing to do is to wait with this marge or maybe marge it and fallowing what i'm adding. 
I love the github UI and when this app will be stable maybe i will move to launchpad.... Just for translation.

**Comment by ghost** [comment]
OK, do not hesitate to contact me when the app will be in a more stable version.
I will be happy to translate the new strings.

**Comment by avisoftware** [comment]
hi @Anne017  now i want to release the next version, i will thank you if you see what i added and translate it, and push it. 
thank you very much for your help!

**Comment by ghost** [comment]
Hi @avisoftware, new strings should be translated now ;)

**Comment by avisoftware** [comment]
Thank you very much!!

**Comment by avisoftware** [comment]
hi @Anne017 i want to release new version, please if you have time to see what changed in the translation  file.
thank you very much for your time!

**Comment by ghost** [comment]
Hi @avisoftware, see #9

**Pull request merged**
